### ISSUE TITLE
Python3 error for Rank news

### ISSUE THREAD

**Issue by newsml** [newsml/newsml#8]
Python3 error for Rank news
```
[2020-01-11 06:02:01,981: ERROR/MainProcess] Task rank_news[e732d776-d3d6-4f9c-8b61-de7060b7eb10] raised unexpected: TypeError('expected string or bytes-like object',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/src/newsml/main/appD.py", line 93, in rank_news
    ranker_instance.rank_articles()
  File "/usr/local/src/newsml/services/ranking/RankerD.py", line 104, in rank_articles
    self.articles = self.get_articles()
  File "/usr/local/src/newsml/services/ranking/RankerD.py", line 94, in get_articles
    self.articles = get_and_rank_news_articles()
  File "/usr/local/src/newsml/services/ranking/ranker.py", line 129, in get_and_rank_news_articles
    if re.match('\d{4}-\d{1,2}-\d{2}', date):
  File "/usr/local/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
[2020-01-11 06:02:55,301: INFO/Worker-1] launch() Process took 173.703170 seconds.```

**Comment by newsml** [comment]
Fixed in https://github.com/newsml/newsml/commit/cef7744f6d311ac2ed4232a75648d5f33dd225ff
