### ISSUE TITLE
Clustering error

### ISSUE THREAD

**Issue by newsml** [newsml/newsml#9]
```
[2020-01-11 06:03:02,434: INFO/Worker-10] Processing 14 articles
[2020-01-11 06:03:02,437: ERROR/MainProcess] Task process_clustering[b17176ba-d96b-4d6d-b9f1-3cceb548f2bd] raised unexpected: TypeError("'<' not supported between instances of 'list' and 'int'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/src/newsml/main/appD.py", line 67, in process_clustering
    clustering_instance.process_articles()
  File "/usr/local/src/newsml/services/clustering/k_means/ClusterD.py", line 302, in process_articles
    self.campaign_reference)
  File "/usr/local/src/newsml/services/clustering/k_means/ClusterD.py", line 168, in insert_records
    sorted_clustered_news_list = sort_articles(clustered_news)
  File "/usr/local/src/newsml/services/clustering/k_means/ClusterD.py", line 96, in sort_articles
    if articles < 1:
TypeError: '<' not supported between instances of 'list' and 'int'
```

**Comment by newsml** [comment]
Fixed
